# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:
- Dólar
- Euro
- Ouro

Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1QHOQt1J7d5Z4sBFKL9GN699OcPh2aVaP?usp=sharing

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

### Agora vamos atualiza a nossa base de preços com as novas cotações

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd

# Abrir o navegador
navegador = webdriver.Chrome()

In [2]:
# Pesquisar e pegar a cotação do Dolar 
navegador.get('https://www.google.com.br/?gws_rd=ssl')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação dolar')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# Pegando informação do Google
cotacao_dolar = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_dolar)

#click() --> Método para clicar em algo na web
#send_keys --> Método para escrecer algo na web

5.6358

In [3]:
# Pesquisar e pegar a cotação do Euro
navegador.get('https://www.google.com.br/?gws_rd=ssl')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação euro')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# Pegando informação do Google
cotacao_euro = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_euro)

6.40283238

In [4]:
# Entrar no site 'Melhor Cambio'
# Pegar a cotação do Ouro
site = 'https://www.melhorcambio.com/ouro-hoje'
navegador.get(site)
cotacao_ouro = navegador.find_element_by_xpath('//*[@id="comercial"]').get_attribute('value')
cotacao_ouro = cotacao_ouro.replace(',', '.')
print(cotacao_ouro)

325.48

In [5]:
tabela_produtos = pd.read_excel('Produtos.xlsx')
display(tabela_produtos)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

In [6]:
# Passo 1: Atualizar as cotações
tabela_produtos.loc[tabela_produtos['Moeda'] == 'Dólar', 'Cotação'] = float(cotacao_dolar)
tabela_produtos.loc[tabela_produtos['Moeda'] == 'Euro', 'Cotação'] = float(cotacao_euro)
tabela_produtos.loc[tabela_produtos['Moeda'] == 'Ouro', 'Cotação'] = float(cotacao_ouro)

# Passo 2: Atualizar o 'Preço Base Reais' ; 'Cotação' * 'Preço Base Original'
tabela_produtos['Preço Base Reais'] = tabela_produtos['Preço Base Original'] * tabela_produtos['Cotação'] 

# Passo 3: Atualizar o 'Preço Final' ; 'Preço Base Reais' * 'Ajuste'
tabela_produtos['Preço Final'] = tabela_produtos['Preço Base Reais'] * tabela_produtos['Ajuste'] 
tabela_produtos['Cotação'] = tabela_produtos['Cotação'].map('{:.2f}'.format)
tabela_produtos['Preço Base Reais'] = tabela_produtos['Preço Base Reais'].map('{:.2f}'.format)
tabela_produtos['Preço Final'] = tabela_produtos['Preço Final'].map('{:.2f}'.format)
display(tabela_produtos)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5.64,5635.74,1.40,7890.04
1,Carro Renault,4500.00,Euro,6.40,28812.75,2.00,57625.49
2,Notebook Dell,899.99,Dólar,5.64,5072.16,1.70,8622.68
3,IPhone,799.00,Dólar,5.64,4503.00,1.70,7655.11
4,Carro Fiat,3000.00,Euro,6.40,19208.50,1.90,36496.14
5,Celular Xiaomi,480.48,Dólar,5.64,2707.89,2.00,5415.78
6,Joia 20g,20.00,Ouro,325.48,6509.60,1.15,7486.04

In [7]:
tabela_produtos.to_excel('Produtos Atualizados.xlsx', index=False)
#index=False ; Não mostrar o indice na exportação do arquivo